/* tslint:disable */
/* eslint-disable */
/**
 * document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArticleIdGet200ResponseCategory } from './article-id-get200-response-category';

/**
 * 
 * @export
 * @interface ArticleIdGet200Response
 */
export interface ArticleIdGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ArticleIdGet200Response
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ArticleIdGet200Response
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIdGet200Response
     */
    'content': string;
    /**
     * 
     * @type {number}
     * @memberof ArticleIdGet200Response
     */
    'categoryId': number;
    /**
     * 
     * @type {string}
     * @memberof ArticleIdGet200Response
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIdGet200Response
     */
    'updatedAt': string;
    /**
     * 
     * @type {ArticleIdGet200ResponseCategory}
     * @memberof ArticleIdGet200Response
     */
    'category': ArticleIdGet200ResponseCategory;
}

