/* tslint:disable */
/* eslint-disable */
/**
 * document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CategoryGet200ResponseInnerCategoriesInnerArticlesInner } from './category-get200-response-inner-categories-inner-articles-inner';

/**
 * 
 * @export
 * @interface ArticleIdGet200ResponseCategory
 */
export interface ArticleIdGet200ResponseCategory {
    /**
     * 
     * @type {number}
     * @memberof ArticleIdGet200ResponseCategory
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof ArticleIdGet200ResponseCategory
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof ArticleIdGet200ResponseCategory
     */
    'parentId': number;
    /**
     * 
     * @type {string}
     * @memberof ArticleIdGet200ResponseCategory
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ArticleIdGet200ResponseCategory
     */
    'updatedAt': string;
    /**
     * 
     * @type {Array<CategoryGet200ResponseInnerCategoriesInnerArticlesInner>}
     * @memberof ArticleIdGet200ResponseCategory
     */
    'articles': Array<CategoryGet200ResponseInnerCategoriesInnerArticlesInner>;
}

