/* tslint:disable */
/* eslint-disable */
/**
 * document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';

/**
 * 
 * @export
 * @interface AuthLoginPost200ResponseToken
 */
export interface AuthLoginPost200ResponseToken {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseToken
     */
    'type': string;
    /**
     * 
     * @type {Null}
     * @memberof AuthLoginPost200ResponseToken
     */
    'name': Null;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseToken
     */
    'token': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthLoginPost200ResponseToken
     */
    'abilities': Array<string>;
    /**
     * 
     * @type {Null}
     * @memberof AuthLoginPost200ResponseToken
     */
    'lastUsedAt': Null;
    /**
     * 
     * @type {Null}
     * @memberof AuthLoginPost200ResponseToken
     */
    'expiresAt': Null;
}

