/* tslint:disable */
/* eslint-disable */
/**
 * document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthLoginPost200ResponseUser
 */
export interface AuthLoginPost200ResponseUser {
    /**
     * 
     * @type {number}
     * @memberof AuthLoginPost200ResponseUser
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseUser
     */
    'role': string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseUser
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseUser
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseUser
     */
    'updatedAt': string;
}

