/* tslint:disable */
/* eslint-disable */
/**
 * document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthLoginPost200ResponseToken } from './auth-login-post200-response-token';
// May contain unused imports in some cases
// @ts-ignore
import type { AuthLoginPost200ResponseUser } from './auth-login-post200-response-user';

/**
 * 
 * @export
 * @interface AuthLoginPost200Response
 */
export interface AuthLoginPost200Response {
    /**
     * 
     * @type {AuthLoginPost200ResponseToken}
     * @memberof AuthLoginPost200Response
     */
    'token': AuthLoginPost200ResponseToken;
    /**
     * 
     * @type {AuthLoginPost200ResponseUser}
     * @memberof AuthLoginPost200Response
     */
    'user': AuthLoginPost200ResponseUser;
}

