/* tslint:disable */
/* eslint-disable */
/**
 * document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';

/**
 * 
 * @export
 * @interface CategoryIdGet200Response
 */
export interface CategoryIdGet200Response {
    /**
     * 
     * @type {number}
     * @memberof CategoryIdGet200Response
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CategoryIdGet200Response
     */
    'title': string;
    /**
     * 
     * @type {Null}
     * @memberof CategoryIdGet200Response
     */
    'parentId': Null;
    /**
     * 
     * @type {string}
     * @memberof CategoryIdGet200Response
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIdGet200Response
     */
    'updatedAt': string;
}

