/* tslint:disable */
/* eslint-disable */
/**
 * document
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CategoryGet200ResponseInnerCategoriesInnerArticlesInner
 */
export interface CategoryGet200ResponseInnerCategoriesInnerArticlesInner {
    /**
     * 
     * @type {number}
     * @memberof CategoryGet200ResponseInnerCategoriesInnerArticlesInner
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CategoryGet200ResponseInnerCategoriesInnerArticlesInner
     */
    'title': string;
    /**
     * 
     * @type {number}
     * @memberof CategoryGet200ResponseInnerCategoriesInnerArticlesInner
     */
    'categoryId': number;
}

